/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.bsuir.kursovoi.chernyak.clientchernyak;

import by.bsuir.kursovoi.chernyak.db.model.Animal;
import by.bsuir.kursovoi.chernyak.logic.AnimalInter;
import by.bsuir.kursovoi.chernyak.logic.BrigadeInter;
import by.bsuir.kursovoi.chernyak.logic.VetInter;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Александр
 */
public class AnimalFilterFrame extends javax.swing.JFrame {
    private List<Animal> animallist;
    private Animal animal;
    private AnimalInter animalinter = null;
    private BrigadeInter brigadeinter = null;
    private VetInter vetinter = null;
    /**
     * Creates new form AnimalFilterFrame
     */
    public AnimalFilterFrame() {
        initComponents();
        try {
            animalinter = StartClient.getEntityManager().getAnimalManager();
            brigadeinter = StartClient.getEntityManager().getBrigadeManager();
            vetinter = StartClient.getEntityManager().getVetManager();
        } catch (RemoteException ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Введите значение  для поиска:");

        jButton1.setText("Поиск по виду");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Назад");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Поиск по породу");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Поиск по полу");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Номер", "Вид", "Порода", "Пол", "Дата поимки", "Место поимки", "Стерилизация", "Номер вольера", "Фамилия ветеринара", "Фамилия отловщика"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jTextField1.getText().isEmpty()){
            
                animallist = animalinter.filterAnimalByKind(jTextField1.getText());

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [animallist.size()][10],
                    new String [] {
                "Номер", "Вид", "Порода", "Пол", "Дата поимки", "Место поимки", "Стерилизация", "Номер вольера", "Фамилия ветеринара", "Фамилия ловца"
                  }
             ));
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
                for (int j = 0; j < animallist.size(); j++) {
                    jTable2.getModel().setValueAt(j+1, j, 0);
                    jTable2.getModel().setValueAt(animallist.get(j).getKind(), j, 1);
                    jTable2.getModel().setValueAt(animallist.get(j).getSpecies(), j, 2);
                    jTable2.getModel().setValueAt(animallist.get(j).getSex(), j, 3);
                    jTable2.getModel().setValueAt(animallist.get(j).getDate_of_capture(), j, 4);
                    jTable2.getModel().setValueAt(animallist.get(j).getPlace_of_capture(), j, 5);
                    jTable2.getModel().setValueAt(animallist.get(j).getSterilization(), j, 6);
                    jTable2.getModel().setValueAt(animallist.get(j).getNum_aviary(), j, 7);
                    jTable2.getModel().setValueAt(vetinter.getSurname(animallist.get(j).getId_vetdoctor()), j, 8);
                    jTable2.getModel().setValueAt(brigadeinter.getSurname(animallist.get(j).getId_brigade()), j, 9);
                    jTable2.setAutoCreateRowSorter(true);
                }
            }
        
         else JOptionPane.showMessageDialog(null, "Введите элемент поиска.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        AnimalFrame animalframe = new AnimalFrame();
        animalframe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!jTextField1.getText().isEmpty()){
            
                animallist = animalinter.filterAnimalBySpecies(jTextField1.getText());

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [animallist.size()][10],
                    new String [] {
                "Номер", "Вид", "Порода", "Пол", "Дата поимки", "Место поимки", "Стерилизация", "Номер вольера", "Фамилия ветеринара", "Фамилия ловца"
                  }
             ));
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
                for (int j = 0; j < animallist.size(); j++) {
                    jTable2.getModel().setValueAt(j+1, j, 0);
                    jTable2.getModel().setValueAt(animallist.get(j).getKind(), j, 1);
                    jTable2.getModel().setValueAt(animallist.get(j).getSpecies(), j, 2);
                    jTable2.getModel().setValueAt(animallist.get(j).getSex(), j, 3);
                    jTable2.getModel().setValueAt(animallist.get(j).getDate_of_capture(), j, 4);
                    jTable2.getModel().setValueAt(animallist.get(j).getPlace_of_capture(), j, 5);
                    jTable2.getModel().setValueAt(animallist.get(j).getSterilization(), j, 6);
                    jTable2.getModel().setValueAt(animallist.get(j).getNum_aviary(), j, 7);
                    jTable2.getModel().setValueAt(vetinter.getSurname(animallist.get(j).getId_vetdoctor()), j, 8);
                    jTable2.getModel().setValueAt(brigadeinter.getSurname(animallist.get(j).getId_brigade()), j, 9);
                    jTable2.setAutoCreateRowSorter(true);
                }
            }
        
         else JOptionPane.showMessageDialog(null, "Введите элемент поиска.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!jTextField1.getText().isEmpty()){
            
                animallist = animalinter.filterAnimalBySex(jTextField1.getText());

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [animallist.size()][10],
                    new String [] {
                "Номер", "Вид", "Порода", "Пол", "Дата поимки", "Место поимки", "Стерилизация", "Номер вольера", "Фамилия ветеринара", "Фамилия ловца"
                  }
             ));
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
                for (int j = 0; j < animallist.size(); j++) {
                    jTable2.getModel().setValueAt(j+1, j, 0);
                    jTable2.getModel().setValueAt(animallist.get(j).getKind(), j, 1);
                    jTable2.getModel().setValueAt(animallist.get(j).getSpecies(), j, 2);
                    jTable2.getModel().setValueAt(animallist.get(j).getSex(), j, 3);
                    jTable2.getModel().setValueAt(animallist.get(j).getDate_of_capture(), j, 4);
                    jTable2.getModel().setValueAt(animallist.get(j).getPlace_of_capture(), j, 5);
                    jTable2.getModel().setValueAt(animallist.get(j).getSterilization(), j, 6);
                    jTable2.getModel().setValueAt(animallist.get(j).getNum_aviary(), j, 7);
                    jTable2.getModel().setValueAt(vetinter.getSurname(animallist.get(j).getId_vetdoctor()), j, 8);
                    jTable2.getModel().setValueAt(brigadeinter.getSurname(animallist.get(j).getId_brigade()), j, 9);
                    jTable2.setAutoCreateRowSorter(true);
                }
            }
        
         else JOptionPane.showMessageDialog(null, "Введите элемент поиска.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.rowAtPoint(evt.getPoint());
        int col = jTable2.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {
            animal = animallist.get(row);
        }
    }//GEN-LAST:event_jTable2MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
